
ALTER TABLE VitaminIndholdsstoffer ADD COLUMN Id VARCHAR(40) NOT NULL AFTER PID
, ADD INDEX Id (Id ASC) ;

ALTER TABLE VitaminUdgaaedeNavne ADD COLUMN Id VARCHAR(40) NOT NULL AFTER PID
, ADD INDEX Id (Id ASC) ;
